[workspace]

members = [
    "parslers-macro",
    "parslers-lib",
    "test-site",
    "parslers-json",
    "parslers-benchmark",
    "parslers-branflakes"
]

[profile.release]
strip = true
lto = true
panic = "abort"
# debug = 1
# codegen-units = 1