[workspace]

members = [
    "parslers-macro",
    "parslers-lib",
    "parslers-json",
    "parslers-benchmark",
    "parslers-branflakes",
    "parslers-wacc"
]

[profile.release]
strip = true
lto = true
panic = "abort"